#Rajnesh Joshi
#You will be asked certain questions
#Answer right or face consequences
#Dark Shock
import time
import random
list = ['']
def crime_scene():
    print("The area is just a damp, bloody stained area")
def opening():
    print(" L I F E   I S   S U F F E R I N G")
    time.sleep(.3)
    print("T H E    W O R L D   I S    U N F A I R")
    time.sleep(.3)
    print("Take Note Of This As You Play")
    time.sleep(.3)
    print("Rajnesh Industries Presents")
    time.sleep(.3)
    print("\n")
    print("\n")
    print(" ▄▀▀█▄▄   ▄▀▀█▄   ▄▀▀▄▀▀▀▄  ▄▀▀▄ █      ▄▀▀▀▀▄  ▄▀▀▄ ▄▄   ▄▀▀▀▀▄   ▄▀▄▄▄▄   ▄▀▀▄ █ ")
    print("█ ▄▀   █ ▐ ▄▀ ▀▄ █   █   █ █  █ ▄▀     █ █   ▐ █  █   ▄▀ █      █ █ █    ▌ █  █ ▄▀ ")
    print("▐ █    █   █▄▄▄█ ▐  █▀▀█▀  ▐  █▀▄         ▀▄   ▐  █▄▄▄█  █      █ ▐ █      ▐  █▀▄  ")
    print("  █    █  ▄▀   █  ▄▀    █    █   █     ▀▄   █     █   █  ▀▄    ▄▀   █        █   █ ")
    print(" ▄▀▄▄▄▄▀ █   ▄▀  █     █   ▄▀   █       █▀▀▀     ▄▀  ▄▀    ▀▀▀▀    ▄▀▄▄▄▄▀ ▄▀   █  ")
    print("█     ▐  ▐   ▐   ▐     ▐   █    ▐       ▐       █   █             █     ▐  █    ▐  ")
    print("▐                          ▐                    ▐   ▐             ▐        ▐       ")
    print("\n")
    print("\n")
    raj=input("What would you like your name to be?: ")
    list.append("raj")
    print([0])
    print("Behind the green dumpster in an alleyway, lies before you")
    print("The Body Of An Unknown Man")
    print("The Face lays deteriorated, and bruised")
    print("Your spine shivers, as you gaze into the cold dead eyes.")
    print("Blood still spews down his mouth, trickles down his soaked shirt")
    print("Officer Jake: Heh, what kinda monsters!")
    print("Officer Jake: Alright! We'll look around here!")
    print("Officer Jake rushes back at an alarming rate, with a piece of evidence to show you")
    print("Surpisingly, came faster than I thought. In Jake's palm, he holds a plastic bag with a bullet covered in blood and flesh")
    print("You gnaw out the flesh and blood with your fingers, and they smush to the side of the plastic bag")
    print("You can see a small label on the bullet, very small, you put on your glasses to read")
    print("P.H. Gun's")
    gunstore_travel=input("Officer Jake:Should we travel to the gun store for more information?: ")
    if gunstore_travel == "no":
        print("Officer Jake: We'll look around for more evidence")
        print("Sorry, Detective, but we couldn't find anything, but we'll stay here and continue looking around")
        print("Here take the bullet with you, and go to PH's")
        list.append("bullet")
        print("Bullet Added To Inventory")
    if gunstore_travel == "yes":
        print("Alright, I'll send a drive to pick you up, here is the bullet")
        list.append("bullet")
        print("Bullet Added To Inventory")
        print("An UBER takes you to PH's and you get off after paying")
        print("You open the door")
def PH_GunStore():
    print("You close the door on the pouring rain, in front of you, a bright red sign 'P.H. Family Owned Gun Store''Shoot em' up varmit'")
    print("Down in front of you is a fat, bow tie wearing, cigar but smelling man, you look on his tag 'Cornelius'")
    print("You ask him for history on the bullet purchase, he hesitates til you show him your badge. He rushes and pulls them out")
    print("Cornelius:Only one person bought that bullet in the past week, T.K")
    print("Cornelius:We got the entire background on this man")
    print("He jams his fingers away on the computer")
    print("Cornelius: Ayyad, in fact hes on the no gun list")
    print("Then why'd you give him the bullet and gun!Look I don't have time for this, Ayyad, huh, print out the information")
    print("You take the sheets of papers")
    list.append("Sheet")
    print("You read the Sheet Of Paper")
    print("Ayyad----Illegal----Wanted")
    print("Ayyad----Threat----Terrorist")
    print("Ayyad----Blue----Crimson---Terrorist----Group")
    print("Why the Damn HELL would they give a gun to him")
    print("A Little Note On The  Blue Crimson Group")
    print("A rich terror organization, they has infiltrated the unknown depths of NY")
    print("Rich terror organization, RICH, thats probably how they got the gun")
    print("Thought to just have only gang wide crimes, they last year, took the lives of many in terror acts all across the city")
    print("This is greater than I thought")
    print("You head back to the NYPD")
def Route_To_NYPD():
    print("You call for a UBER")
    print("The car rolls up")
    print("The driver, a brown man driving, and a white man next to him")
    print("I thought this was my taxi")
    print("Quiet, his destination is up ahead, just relax")
    print("The man seemed tensed")
    leavecar=input("Do you want out of the car?: ")
    if leavecar == "yes":
        print(raj,"I am going to go now")
        time.sleep(.3)
        print("You leave the car")
        time.sleep(.3)
        print("The car screeches away")
        time.sleep(.3)
        print("Something seems very wrong")
        time.sleep(.3)
        print("Just that man, the situation")
        time.sleep(.3)
        print("Very Very Odd")
        time.sleep(.3)
        print("You decide to walk, its only a 20 minute walk")
        print("You walk down the first street")
        print("It is raining very loud, and you are getting soaked")
        UBERUP=input("Do you want to call back the UBER or go on")
        if UBERUP == "yes":
            print("After clicking the app on your phone, you find that the only one available was the previous one")
            print("Pretty odd, but you don't think much about it")
            print("The same guy comes again, and the white man seated next to him is still there")
            print("You without question, decide to take it, it's your only choice rather than walking in the rain")
            print("You ask for NYPD departement, Riller Street")
            print("The car takes a few wrong turns, but the silence felt nice, and so did the ride")
            print("So you don't compain")
            print("But then you get onto the highway, and things take a turn")
            print("Immediately you jump to the question of what the hell is going on")
            print("Brown Man: I am going to quickly drop him off first!")
            print("30 minutes in, you arrive to a warehouse")
            print("The brown man, calls the white man Mason, and to the other Armeh")
            print("They converse the entire time, so you picked the names up")
            print("You reach the Warehouse, and Mason gets off, but so does Armeh")
            print("They open your seat door and yell")
            print("Armeh: Get the HELL OUT!")
            print("With no thought process, you put your hands up, and walk alongside them")
            print("That is it")
            time.sleep(10)
            print("You wake up in the middle of a room, tied up")
        if UBERUP == "no":
            print("You reach the stoplight")
            print("You hear the tires screeching down the street, at a fast rate")
            print("You look around to see it was your previous UBER")
            print("Both men still in the vehicle")
            print("Without hesitation you try to get out of the way")
            print("But the car was too fast, and slides straight into you")
            print("Your down on the ground")
            print("Your head is throbbing")
            print("You cannot feel anything")
            print("It has become difficult to breathe")
            print("Both men run up to you")
            print("And one of them throws up your body, and searches for the papers")
            print("He takes it, and rips it up and both rush back to their car")
            print("You are left there to die")
            print("The rain just keeps pouring in, and the crowd around you swarms up faster")
            print("The pain is just too much to bear, you throwyourself onto your side")
            print("However, the ambulance was taking too long. New york traffic is horrid")
            print("You sit there, til your final minute arrived")
            print("You have died from story circumstances")
            quit()
    if leavecar == "no":
            print("You ask for NYPD departement, Riller Street")
            print("The car takes a few wrong turns, but the silence felt nice, and so did the ride")
            print("So you don't compain")
            print("But then you get onto the highway, and things take a turn")
            print("Immediately you jump to the question of what the hell is going on")
            print("Brown Man: I am going to quickly drop him off first!")
            print("30 minutes in, you arrive to a warehouse")
            print("The brown man, calls the white man Mason, and to the other Armeh")
            print("They converse the entire time, so you picked the names up")
            print("You reach the Warehouse, and Mason gets off, but so does Armeh")
            print("They open your seat door and yell")
            print("Armeh: Get the HELL OUT!")
            print("With no thought process, you put your hands up, and walk alongside them")
            print("That is it")
            time.sleep(10)
            print("You wake up in the middle of a room, tied up")
def Warehouse():
    print("the pockets were cleared out and searched through")
    print("Ayadd's sheets were missing from the pocket")
    print("The sound of footsteps approaches down the hallways")
    print("You are tied up very well")
    print("Type 1-Search Back Pocket")
    print("Type 2-Try to wiggle loose")
    chair_exit=input("...: ")
    if chair_exit == "1":
        print("You find a bullet, its the one Officer Jake gave for you too use")
        rope_cut=input("Would you like to use it to attempt to cut through the ropes?: ")
        if rope_cut == "yes":
            print("The bullet is in your palm and you push it up to your fingers and you start cutting")
            print("You try slitting the rope slowly and slowly")
            print("The threads are falling lose and they are coming off")
            print("That is good news, but bad news, the footsteps are extremely close")
            print("You decide to put the bullet back into your pocket, and cover the weakest part in the ropes")
            print("The footsteps are almost there")
            print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
            print("You've made the assumption that he is like the boss around the place")
            print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")
            print("Armeh: Ehh Boss")
            print("He looks at you and realizes you're in the room")
            print("Armeh: Ohh")
            print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
            print("Dmitri shakes his head")
            print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
            print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
            print("Dmitri: JUST")
            print("Dmitri: GET")
            print("Dmitri: TO")
            print("Dmitri: THE")
            print("Dmitri: POINT!")
            print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
            print("Dmitri: Remember when we talked about how not to discreetly blurt out plans out loud to authority")
            print("Armeh now has a stupid look on his face, and too say very well, it was funny, but this is no laughing matter")
            print("Armeh:Uh, oh geez boss, sorry I really did forget")
            print("Mason walks in, and he seems serious and clever enough to be in the business")
            print("Makes you wonder how the hell did Armeh get here in the first place")
            print("Whatever, Mason looks at Armeh")
            print("Broken plate on the ground")
            print("The 'Boss', Dmitri")
            print("And you")
            print("He has made the assumption from the knowledge he takes")
            print("And probably already knows of Armeh being a clutz")
            print("He walks up to Armeh and slaps him on the head")
            print("Mason: Ehh, what is the mattahhh with you, we runnin' a business ehh, and you trynna' be stupid here")
            print("Armeh: I swear it was a mistake")
            print("Dmitri: Mason, how about we go get some brunch")
            print("Brunch, but weren't you kidnapped at night time")
            print("It must've been a day atleast since I arrived at this junkhouse")
            print("Mason:That I can do")
            print("Armeh: What about me Boss")
            print("Dmitri: You can watch")
            print("Dmitri opens the door and they all begin to exit")
            print("Armeh: Aw, I always have to watch")
            print("Dmitri: Well maybe when you learn not to...")
            print("There voices begin to become mutters, and they stray off as the three walk down the hallway")
            print("Well I still gotta get outta here, and maybe get some brunch after")
        if rope_cut == "no":
            print("You wait for the person to come into the room")
            print("He walks in, a blue eyed bald russian, tall and strong enough to break bricks with his finger")
            print("He is a bit slim, and takes most of his muscle to his arms but that doesn't change the situation and the fact that this man is not one to mess around with")
            print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
            print("You've made the assumption that he is like the boss around the place")
            print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")
            print("Armeh: Ehh Boss")
            print("He looks at you and realizes you're in the room")
            print("Armeh: Ohh")
            print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
            print("Dmitri shakes his head")
            print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
            print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
            print("Dmitri: JUST")
            print("Dmitri: GET")
            print("Dmitri: TO")
            print("Dmitri: THE")
            print("Dmitri: POINT!")
            print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
            print("Dmitri: Remember when we talked about how not to discreetly blurt out plans out loud to authority")
            print("Armeh now has a stupid look on his face, and too say very well, it was funny, but this is no laughing matter")
            print("Armeh:Uh, oh geez boss, sorry I really did forget")
            print("Mason walks in, and he seems serious and clever enough to be in the business")
            print("Makes you wonder how the hell did Armeh get here in the first place")
            print("Whatever, Mason looks at Armeh")
            print("Broken plate on the ground")
            print("The 'Boss', Dmitri")
            print("And you")
            print("He has made the assumption from the knowledge he takes")
            print("And probably already knows of Armeh being a clutz")
            print("He walks up to Armeh and slaps him on the head")
            print("Mason: Ehh, what is the mattahhh with you, we runnin' a business ehh, and you trynna' be stupid here")
            print("Armeh: I swear it was a mistake")
            print("Dmitri: Mason, how about we go get some brunch")
            print("Brunch, but weren't you kidnapped at night time")
            print("It must've been a day atleast since I arrived at this junkhouse")
            print("Mason:That I can do")
            print("Armeh: What about me Boss")
            print("Dmitri: You can watch")
            print("Dmitri opens the door and they all begin to exit")
            print("Armeh: Aw, I always have to watch")
            print("Dmitri: Well maybe when you learn not to...")
            print("There voices begin to become mutters, and they stray off as the three walk down the hallway")
            print("Well I still gotta get outta here, and maybe get some brunch after")           
    if chair_exit == "2":
        print("You push your weight back and forth")
        print("Swaying back and forth")
        print("The rope doesn't get any more loose but you continue anyways")
        print("Youv'e pushed way too hard and you've fallen onto your back")
        print("You can hear the footsteps now rushing towards your room")
        print("And a voice, you make out that it is a russian")
        print("Russian Voice Unknown: What the!")
        print("He walks up to the doorway, there is no door, it is just an open space")
        print("Russian Voice Unknown: What in the Riyelecki are you trying to do")
        print("He walks up to you, and he picks you up while your'e still on the chair")
        print("Dmitri: That was just stupid...Trying to escape...No way out buddy, your here for a very long long time, the names Dmitri, do you even know who we are")
        print(raj,"You spit in his face")
        print("He wipes it off, he seems to be a very understanding man, bald man, tall and strong")
        print("He spits back and punches you straight in the head")
        print("Smushing your face with his huge fist, looks like he isn't very understanding")
        print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
        print("You've made the assumption that he is like the boss around the place")
        print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")
        print("Armeh: Ehh Boss")
        print("He looks at you and realizes you're in the room")
        print("Armeh: Ohh")
        print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
        print("Dmitri shakes his head")
        print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
        print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
        print("Dmitri: JUST")
        print("Dmitri: GET")
        print("Dmitri: TO")
        print("Dmitri: THE")
        print("Dmitri: POINT!")
        print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
        print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
        print("Dmitri: Remember when we talked about how not to discreetly blurt out plans out loud to authority")
        print("Armeh now has a stupid look on his face, and too say very well, it was funny, but this is no laughing matter")
        print("Armeh:Uh, oh geez boss, sorry I really did forget")
        print("Mason walks in, and he seems serious and clever enough to be in the business")
        print("Makes you wonder how the hell did Armeh get here in the first place")
        print("Whatever, Mason looks at Armeh")
        print("Broken plate on the ground")
        print("The 'Boss', Dmitri")
        print("And you")
        print("He has made the assumption from the knowledge he takes")
        print("And probably already knows of Armeh being a clutz")
        print("He walks up to Armeh and slaps him on the head")
        print("Mason: Ehh, what is the mattahhh with you, we runnin' a business ehh, and you trynna' be stupid here")
        print("Armeh: I swear it was a mistake")
        print("Dmitri: Mason, how about we go get some brunch")
        print("Brunch, but weren't you kidnapped at night time")
        print("It must've been a day atleast since I arrived at this junkhouse")
        print("Mason:That I can do")
        print("Armeh: What about me Boss")
        print("Dmitri: You can watch")
        print("Dmitri opens the door and they all begin to exit")
        print("Armeh: Aw, I always have to watch")
        print("Dmitri: Well maybe when you learn not to...")
        print("There voices begin to become mutters, and they stray off as the three walk down the hallway")
        print("Well I still gotta get outta here, and maybe get some brunch after")
def TK_Truth():
    print(([0])
    print("He looks like he knows a few things")
    print("And most definetly needs help")
    print("You kneel down, to the poor guys face")
    print("First you untie him")
    print("He coughs out some blood, possible because of torture")
    print("Hostage: Hello...Thank...You...")
    print("He cries onto your shoulder")
    print("Hostage:  Please...The things they are going to do")
    print("Hostage: The things they have done")
    print("What have they done to you")
    print("Hostage:For the past few days, I have been under the torture of there leaders and henchmen")
    print("Hostage: I haven't seen my children in weeks")
    print("Hostage:I will tell you what they have done, as a thank you")
    print("Hostage: They killed my brother, Tony, apparently he walked too close into some of there business")
    print("Hostage: So they shot him dead behind an alleyway, and took me under close surveillance and decided to torture me")
    print("What business? What are they up to")
    print("Hostage: Look I don't know exactly, but whatever it is it is in that room over there")
    print("He points to a locked room")
    print("I will find out what is in there")
    print("You stand up, and find the door is locked")
    print("However, there is a guard at the front of the Warehouse")
    print("Type 1-Take him out, take his key")
    print("Type 2-Or, look around")
    keylook=input("How will you look: ")
    if keylook == "1":
        print("You walk slowly up to the entrance of the room")
        print("Being very quiet")
        print("You slowly get up behind him, and you put under a choke hold")
        print("You suffocate him to the floor")
        print("You search for the key, its on his neck")
        print("You take it")
        list.append("key")
        print("After you tear it off, you walk back to the unknown room")
    if keylook == "2":
        print("Decide not to take the risk")
        print("You see a key laying on the counter, across the hallway")
        print("Type 1-Don't take it and get the key from the security guard")
        print("Type 2-Sneak Past and take they key")
        hallwaykey=input("What will you do?: ")
        if hallwaykey == "1":
            print("After hesitating, you decide to go for the less risky way under your assumption")
            print("You walk slowly up to the entrance of the room")
            print("Being very quiet")
            print("You slowly get up behind him, and you put under a choke hold")
            print("You suffocate him to the floor")
            print("You search for the key, its on his neck")
            print("You take it")
            list.append("key")
            print("After you tear it off, you walk back to the unknown room")
        if hallwaykey == "2":
            print("You slowly etch toward they table")
            print("The floor creaks too loud")
            print("The guard yells, but rather than stopping you")
            print("He pulls a gun out of his pocket and fires")
            print("You fall to the ground in your own blood, all seen by the hostage looking through his window")
            print("GameOver, you have died under story circumstances")
            quit()
def BombHouse():
    print(":")
def Ledge():
    print("You have the bomb in your grasp")
    print("Your up to the edge of the window")
    print("It is a great drop into the ocean water, and jagged rocks")
    print("The distance between you and the three, but it behind them are more")
    print("They stand at the door, slowly getting closer")
    print("Any damn closer and I blow up this abandonedwarehouse")
    print("They do not hesitate to back up")
    print("He is not afraid to take action, Dmitry means business")
    print("He slowly reaches for his gun, and shoots the hostage for telling you")
    print("The bullet goes straight through him")
    print("He falls to his knees")
    print("He falls onto his stomach, his life is at an end")
    print("This disgusting act")
    print("These damn disgusting people")
    print("You just...You just...")
    sacrifice=input("You have the choice to take the bomb down with you, would you like to do it")
    if sacrifice == "yes":
        print("Dmitry fires another bullet straight through chest, missing the bomb in your hands")
        print("You sway back and forth, your last gasps for breath go in and out")
        print("You hold close to the bomb, and sway yourself outside the ledge")
        print("You 40 feet, down to the jagged rocks, and with the bomb with you")
        time.sleep(1)
        print("Unfortuanately it sets off")
        time.sleep(1)
        print("Everyone at the abandoned warehouse dies")
        time.sleep(1)
        print("The plans of the Blue Crimson gang were foiled by you and you saved New York, you took them down with you")
        time.sleep(1)
        print("No one saw your act.")
        time.sleep(1)
        print("No")
        time.sleep(1)
        print("One")
        time.sleep(1)
        print("Will")
        time.sleep(1)
        print("Your")
        time.sleep(1)
        print("Sacrifice")
    if sacrifice == "no":
        print("Alright!")
        print("You step off the ledge")
        print("The faces of each gang members turns relaxed")
        sacrificeask2=input("Are you sure you want to do this?: ")
        if sacrificeask2 == "yes":
            print("You continue slowly")
            print("Still holding strongly onto the bomb")
            print("Dmitri is the first one to step first")
            print("He grabs the bomb from you hand")
            print("With a great smile he can finally say")
            print("Dmitri: It's over")
            time.sleep(2)
            print("Dmitri: And")
            time.sleep(2)
            print("Dmitri: Thank")
            time.sleep(2)
            print("Dmitri: Very")
            time.sleep(2)
            print("Dmitri: Much")
            print("He pulls a gun from his back pocket")
            print("And puts it right next to your forehead")
            print("You've been cheated so badly")
            print("You went the coward way, and unfortuanetely, you die the coward way")
            print("Your face is red")
            print("And your eyes start to water")
            time.sleep(2)
            print("Game Over")
            time.sleep(2)
            print("Thank you for playing")
def credit():
    print("Thank You For Playing")
    print("Created By")
    print("       Rajnesh       Joshi            ")
opening()
PH_GunStore()
Route_To_NYPD()
Warehouse()
TK_Truth()
BombHouse()
Ledge()
credit()
