def warehouse():
    print("the pockets were cleared out and searched through")
    print("Ayadd's sheets were missing from the pocket")
    print("The sound of footsteps approaches down the hallways")
    print("You are tied up very well")
    print("Type 1-Search Back Pocket")
    print("Type 2-Try to wiggle loose")
    chair_exit=input("...: ")
    if chair_exit == "1":
        print("You find a bullet, its the one Officer Jake gave for you too use")
        rope_cut=input("Would you like to use it to attempt to cut through the ropes?: ")
        if rope_cut == "yes":
            print(List[(1)])
            print("The bullet is in your palm and you push it up to your fingers and you start cutting")
            print("You try slitting the rope slowly and slowly")
            print("The threads are falling lose and they are coming off")
            print("That is good news, but bad news, the footsteps are extremely close")
            print("You decide to put the bullet back into your pocket, and cover the weakest part in the ropes")
            print("The footsteps are almost there")
            print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
            print("You've made the assumption that he is like the boss around the place")
            print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")\
            print("Armeh: Ehh Boss")
            print("He looks at you and realizes you're in the room")
            print("Armeh: Ohh")
            print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
            print("Dmitri shakes his head")
            print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
            print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
            print("Dmitri: JUST")
            print("Dmitri: GET")
            print("Dmitri: TO")
            print("Dmitri: THE")
            print("Dmitri: POINT!")
            print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
        if rope_cut == "no":
            print("You wait for the person to come into the room")
            print("He walks in, a blue eyed bald russian, tall and strong enough to break bricks with his finger")
            print("He is a bit slim, and takes most of his muscle to his arms but that doesn't change the situation and the fact that this man is not one to mess around with")
            print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
            print("You've made the assumption that he is like the boss around the place")
            print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")
            print("Armeh: Ehh Boss")
            print("He looks at you and realizes you're in the room")
            print("Armeh: Ohh")
            print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
            print("Dmitri shakes his head")
            print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
            print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
            print("Dmitri: JUST")
            print("Dmitri: GET")
            print("Dmitri: TO")
            print("Dmitri: THE")
            print("Dmitri: POINT!")
            print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
            print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
    if chair_exit == "2":
        print("You push your weight back and forth")
        print("Swaying back and forth")
        print("The rope doesn't get any more loose but you continue anyways")
        print("Youv'e pushed way too hard and you've fallen onto your back")
        print("You can hear the footsteps now rushing towards your room")
        print("And a voice, you make out that it is a russian")
        print("Russian Voice Unknown: What the!")
        print("He walks up to the doorway, there is no door, it is just an open space")
        print("Russian Voice Unknown: What in the Riyelecki are you trying to do")
        print("He walks up to you, and he picks you up while your'e still on the chair")
        print("Dmitri: That was just stupid...Trying to escape...No way out buddy, your here for a very long long time, the names Dmitri, do you even know who we are")
        print(raj,"You spit in his face")
        print("He wipes it off, he seems to be a very understanding man, bald man, tall and strong")
        print("He spits back and punches you straight in the head")
        print("Smushing your face with his huge fist, looks like he isn't very understanding")
        print("Dmitri: Detective, you obviously don't know who we are...Armeh GET IN HERE!")
        print("You've made the assumption that he is like the boss around the place")
        print("The brown UBER driver walks in, he has yellow gloves on, one hand has a plate in it, and the other a scrubber, he is wearing an apron")\
        print("Armeh: Ehh Boss")
        print("He looks at you and realizes you're in the room")
        print("Armeh: Ohh")
        print("He drops the plate, it breaks on the floor he takes the gloves and puts that and the scrubber on a metal table")
        print("Dmitri shakes his head")
        print("Dmitri:Alright Armeh, can you tell our little guest here who we are")
        print("Armeh: Okay Boss, look'ie here kiddo, were the biggest, baddest, bombastic, brutalist, brobdingnagian..")
        print("Dmitri: JUST")
        print("Dmitri: GET")
        print("Dmitri: TO")
        print("Dmitri: THE")
        print("Dmitri: POINT!")
        print("Armeh: Geez...Sorry..Boss..Okay were was I. brobdingnagian blue crimson gang")
        print("Armeh: You think this place is a joke, cause it is far from one, we got a big plan on our sleeves and you seem to be messing with us")
        print("Dmitri: Remember when we talked about how not to discreetly blurt out plans out loud to authority")
        print("Armeh now has a stupid look on his face, and too say very well, it was funny")
        print("Armeh:
